// <auto-generated />
namespace REITs.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _11091 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11091));
        
        string IMigrationMetadata.Id
        {
            get { return "201909111039351_1109.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
