// <auto-generated />
namespace REITs.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _24072 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_24072));
        
        string IMigrationMetadata.Id
        {
            get { return "201907241658108_2407.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
